"""Realm — a self-contained text fantasy-kingdom management game.

You are the ruler: set taxes, build your realm, marry, wage war, and keep your
dynasty on the throne. Every character, event, war and price is generated by the
simulation. No network, no APIs, no external data — Python stdlib only.

Run interactively:   python kingdom.py
Run the self-play harness: python kingdom.py --selfplay [seeds] [turns]

# ponytail: one module holds engine + CLI + harness. Split only if a second
# front-end (web/TUI) ever needs the engine alone.
"""
from __future__ import annotations
import random
import sys
from dataclasses import dataclass, field

# --------------------------------------------------------------------------- #
# Procedural name/content generation (no external data)
# --------------------------------------------------------------------------- #
_PRE = ["Al", "Ber", "Cor", "Dra", "Ed", "Gar", "Hal", "Ist", "Jor", "Kael",
        "Lor", "Mor", "Nor", "Os", "Per", "Rho", "Ser", "Tor", "Ul", "Vor",
        "Wil", "Yr", "Aen", "Bran", "Cael", "Dun"]
_MALE = ["wen", "dric", "mund", "gar", "ric", "bert", "mir", "lan", "dor",
         "win", "fred", "helm", "stan", "ulf", "mar", "var"]
_FEM = ["wyn", "ana", "ella", "ira", "essa", "lin", "wen", "ith", "ara",
        "isse", "iel", "yra", "ona", "elle"]
_PLACE = ["mark", "gard", "helm", "fell", "wood", "moor", "vale", "reach",
          "hold", "ford", "crag", "mere", "wick", "dale"]
_TRAITS = ["Just", "Cruel", "Brave", "Craven", "Shrewd", "Naive", "Pious",
           "Greedy", "Generous", "Wrathful", "Patient", "Ambitious"]


def _name(rng: random.Random, gender: str) -> str:
    tail = _MALE if gender == "m" else _FEM
    return rng.choice(_PRE) + rng.choice(tail)


def _place(rng: random.Random) -> str:
    return rng.choice(_PRE) + rng.choice(_PLACE)


# --------------------------------------------------------------------------- #
# Data model
# --------------------------------------------------------------------------- #
@dataclass
class Person:
    pid: int
    name: str
    gender: str          # 'm' | 'f'
    age: int
    rel: str             # 'ruler' | 'spouse' | 'child' | 'sibling'
    martial: int
    stewardship: int
    diplomacy: int
    intrigue: int
    traits: list = field(default_factory=list)
    alive: bool = True

    @property
    def title(self) -> str:
        return f"{self.name} ({self.age})"


@dataclass
class Neighbor:
    name: str
    relation: int        # -100..100
    strength: int        # army size
    at_war: bool = False
    cooldown: int = 0     # turns until war can be re-declared/invasion resumes


@dataclass
class Realm:
    name: str
    treasury: int        # gold, integer; may go negative (debt)
    population: int      # subjects
    prosperity: int      # 0..100
    stability: int       # 0..100
    legitimacy: int      # 0..100
    army: int            # soldiers
    tax_rate: int        # 0..100 (percent)


@dataclass
class Game:
    seed: int
    rng: random.Random
    turn: int
    year: int
    realm: Realm
    ruler: Person
    family: list         # Persons other than the ruler (spouse/child/sibling)
    neighbors: list
    next_pid: int
    log: list = field(default_factory=list)
    over: bool = False
    over_reason: str = ""
    last_event: str = ""   # name of the previous turn's event, to avoid repeats

    def emit(self, msg: str) -> None:
        self.log.append(msg)


STAT_FIELDS = ("prosperity", "stability", "legitimacy")


def _clamp(v: int, lo: int = 0, hi: int = 100) -> int:
    return max(lo, min(hi, v))


def _make_person(rng: random.Random, pid: int, rel: str, age: int,
                 gender: str | None = None) -> Person:
    gender = gender or rng.choice(["m", "f"])
    return Person(
        pid=pid,
        name=_name(rng, gender),
        gender=gender,
        age=age,
        rel=rel,
        martial=rng.randint(1, 20),
        stewardship=rng.randint(1, 20),
        diplomacy=rng.randint(1, 20),
        intrigue=rng.randint(1, 20),
        traits=rng.sample(_TRAITS, k=2),
    )


def _new_person(g: Game, rel: str, age: int, gender: str | None = None) -> Person:
    p = _make_person(g.rng, g.next_pid, rel, age, gender)
    g.next_pid += 1
    return p


def new_game(seed: int) -> Game:
    rng = random.Random(seed)
    realm = Realm(
        name=_place(rng),
        treasury=200,
        population=5000,
        prosperity=50,
        stability=60,
        legitimacy=60,
        army=300,
        tax_rate=25,
    )
    # Ruler: young, married, one young child -> a reign can plausibly last 30 turns.
    ruler = _make_person(rng, 1, "ruler", age=rng.randint(22, 30))
    g = Game(
        seed=seed, rng=rng, turn=0, year=1000 + rng.randint(0, 200),
        realm=realm, ruler=ruler, family=[], neighbors=[], next_pid=2,
    )
    spouse_gender = "f" if ruler.gender == "m" else "m"
    g.family.append(_new_person(g, "spouse", age=ruler.age - rng.randint(-3, 4),
                                gender=spouse_gender))
    g.family.append(_new_person(g, "child", age=rng.randint(0, 6)))
    # A sibling, as a fallback heir.
    g.family.append(_new_person(g, "sibling", age=ruler.age + rng.randint(-6, 6)))
    # Three neighbouring realms for diplomacy/war.
    for _ in range(3):
        g.neighbors.append(Neighbor(
            name=_place(rng),
            relation=rng.randint(-30, 40),
            strength=rng.randint(150, 500),
        ))
    return g


# --------------------------------------------------------------------------- #
# Helpers for living relatives
# --------------------------------------------------------------------------- #
def _living(g: Game, rel: str) -> list:
    return [p for p in g.family if p.alive and p.rel == rel]


def _spouse(g: Game) -> Person | None:
    s = _living(g, "spouse")
    return s[0] if s else None


# --------------------------------------------------------------------------- #
# Events: procedurally filled templates. Each option has a mechanical effect.
# An effect returns a short result string; it MUST change game state.
# --------------------------------------------------------------------------- #
def _apply(g: Game, *, treasury=0, prosperity=0, stability=0,
           legitimacy=0, army=0, population=0) -> None:
    r = g.realm
    r.treasury += treasury
    r.army = max(0, r.army + army)
    r.population = max(0, r.population + population)
    r.prosperity = _clamp(r.prosperity + prosperity)
    r.stability = _clamp(r.stability + stability)
    r.legitimacy = _clamp(r.legitimacy + legitimacy)


def _event_plague(g):
    region = _place(g.rng)
    prompt = f"Plague spreads through {region}. The dying cry for aid."
    def fight():
        _apply(g, treasury=-60, stability=+4, population=-200)
        return "You fund physicians. Coffers lighter, the realm grateful."
    def ignore():
        _apply(g, population=-700, stability=-8, prosperity=-5)
        return "You do nothing. The plague rages; villages empty."
    return prompt, [("Fund physicians (-60g)", fight), ("Let it run its course", ignore)]


def _event_plot(g):
    schemer = g.rng.choice(_living(g, "sibling") + _living(g, "child")) \
        if (_living(g, "sibling") or _living(g, "child")) else None
    who = schemer.name if schemer else _name(g.rng, "m")
    prompt = f"Whispers reach you: {who} plots to seize your throne."
    def execute():
        win = g.rng.random() < (0.4 + g.ruler.intrigue / 40)
        if win:
            if schemer:
                schemer.alive = False
            _apply(g, stability=+5, legitimacy=-4)
            return f"{who} is executed at dawn. A warning to all."
        _apply(g, stability=-10, legitimacy=-8)
        return f"The arrest fails. {who} escapes and your weakness shows."
    def pardon():
        _apply(g, legitimacy=-6, stability=+2)
        return f"You pardon {who}. Mercy, or weakness — the court murmurs."
    def bribe():
        _apply(g, treasury=-50, stability=+3)
        return f"Gold buys {who}'s loyalty. For now."
    return prompt, [("Execute the schemer", execute),
                    ("Pardon them", pardon),
                    ("Buy their loyalty (-50g)", bribe)]


def _event_harvest(g):
    prompt = "Stewards report an unusually fertile season."
    def tax_surplus():
        _apply(g, treasury=+50, prosperity=+3)
        return "You tax the surplus grain. The treasury swells."
    def store():
        _apply(g, prosperity=+8, stability=+3)
        return "You let folk keep the bounty. Prosperity grows."
    return prompt, [("Tax the surplus (+50g)", tax_surplus),
                    ("Let the people keep it", store)]


def _event_knight(g):
    knight = _name(g.rng, "m")
    prompt = f"A wandering sellsword, {knight}, offers their blade."
    def hire():
        _apply(g, treasury=-40, army=+80)
        return f"{knight} and their company join your host."
    def decline():
        _apply(g, stability=-1)
        return f"You send {knight} away. They mutter as they go."
    return prompt, [("Hire the company (-40g)", hire), ("Decline", decline)]


def _event_unrest(g):
    region = _place(g.rng)
    prompt = f"Peasants in {region} riot over their burdens."
    def crush():
        _apply(g, army=-20, stability=+6, population=-150, legitimacy=-3)
        return "Soldiers crush the revolt. Order returns, at a cost."
    def concede():
        _apply(g, treasury=-30, stability=+4, prosperity=+2)
        return "You ease their burdens. The riots fade."
    return prompt, [("Crush the revolt", crush),
                    ("Make concessions (-30g)", concede)]


def _event_envoy(g):
    n = g.rng.choice(g.neighbors)
    prompt = f"An envoy from {n.name} proposes a trade pact."
    def accept():
        n.relation = _clamp(n.relation + 20, -100, 100)
        _apply(g, treasury=+30, prosperity=+3)
        return f"Trade with {n.name} flourishes."
    def refuse():
        n.relation = _clamp(n.relation - 10, -100, 100)
        return f"You spurn {n.name}'s offer. They take it ill."
    return prompt, [("Accept the pact", accept), ("Refuse", refuse)]


EVENTS = [_event_plague, _event_plot, _event_harvest, _event_knight,
          _event_unrest, _event_envoy]


# --------------------------------------------------------------------------- #
# Decrees: the player's deliberate action each turn. Options are built from the
# current state so only valid actions appear. Each returns a result string.
# --------------------------------------------------------------------------- #
def decree_options(g: Game):
    r = g.realm
    opts = []

    def raise_tax():
        r.tax_rate = _clamp(r.tax_rate + 10)
        return f"Taxes raised to {r.tax_rate}%."
    opts.append(("Raise taxes (+10%)", raise_tax))

    def lower_tax():
        r.tax_rate = _clamp(r.tax_rate - 10)
        return f"Taxes lowered to {r.tax_rate}%."
    opts.append(("Lower taxes (-10%)", lower_tax))

    def invest():
        _apply(g, treasury=-50, prosperity=+6)
        return "You fund roads and markets. Prosperity rises."
    opts.append(("Invest in the realm (-50g)", invest))

    def recruit():
        _apply(g, treasury=-40, army=+100)
        return "Fresh levies swell your army."
    opts.append(("Recruit soldiers (-40g)", recruit))

    def feast():
        _apply(g, treasury=-30, stability=+5, legitimacy=+3)
        return "A grand feast lifts spirits across the realm."
    opts.append(("Hold a feast (-30g)", feast))

    # Diplomacy: improve the worst relation.
    worst = min(g.neighbors, key=lambda n: n.relation)
    def court_neighbor():
        worst.relation = _clamp(worst.relation + 25, -100, 100)
        _apply(g, treasury=-30)
        return f"Gifts and envoys warm relations with {worst.name}."
    opts.append((f"Send gifts to {worst.name} (-30g)", court_neighbor))

    # Ruler marriage: an unmarried ruler may take a spouse, so the line can
    # continue. Without this, an heir who ascends young and childless is doomed.
    if g.ruler.age >= 16 and _spouse(g) is None:
        def wed_ruler():
            sg = "f" if g.ruler.gender == "m" else "m"
            sp = _new_person(g, "spouse",
                             age=max(16, g.ruler.age - g.rng.randint(0, 5)),
                             gender=sg)
            g.family.append(sp)
            _apply(g, treasury=-40, legitimacy=+3)
            return f"You wed {sp.name}; the court celebrates a royal union."
        opts.append(("Take a spouse (-40g)", wed_ruler))

    # Marriage alliance: marry off an eligible child — but only if it leaves at
    # least one heir behind (never marry away your last heir).
    eligible = [c for c in _living(g, "child") if c.age >= 16]
    heirs = _living(g, "child") + _living(g, "sibling")
    if eligible and len(heirs) >= 2:
        child = eligible[0]
        ally = max(g.neighbors, key=lambda n: n.relation)
        def marry():
            ally.relation = _clamp(ally.relation + 40, -100, 100)
            _apply(g, legitimacy=+4)
            child.rel = "married_out"  # no longer a primary heir
            return f"{child.name} weds into {ally.name}. An alliance is sealed."
        opts.append((f"Wed {child.name} to {ally.name}", marry))

    # War: declare on a hostile neighbour (not already at war, not on cooldown).
    hostile = [n for n in g.neighbors
               if n.relation < 0 and not n.at_war and n.cooldown == 0]
    if hostile:
        target = min(hostile, key=lambda n: n.relation)
        def declare():
            target.at_war = True
            _apply(g, stability=-4)
            return f"War! You march against {target.name}."
        opts.append((f"Declare war on {target.name}", declare))

    def hold():
        _apply(g, stability=+1)
        return "You hold court and tend to petitions."
    opts.append(("Hold court (do nothing bold)", hold))

    return opts


# --------------------------------------------------------------------------- #
# Turn phases
# --------------------------------------------------------------------------- #
def phase_economy(g: Game) -> None:
    r = g.realm
    for n in g.neighbors:
        if n.cooldown > 0:          # war cooldowns tick down each turn
            n.cooldown -= 1
        if g.rng.random() < 0.15:   # rival realms slowly arm over the decades
            n.strength += g.rng.randint(10, 40)
    steward = g.ruler.stewardship
    income = (r.population * r.tax_rate) // 1000 + (r.prosperity // 4) + steward
    upkeep = r.army // 4
    r.treasury += income - upkeep
    g.emit(f"Treasury: +{income} income, -{upkeep} upkeep "
           f"(now {r.treasury}g).")

    # Tax pressure and debt feed back into stability/prosperity.
    if r.tax_rate > 40:
        r.stability = _clamp(r.stability - (r.tax_rate - 40) // 10)
    if r.treasury < 0:
        # Debt bites harder the deeper it runs: -3 plus -1 per 1000g owed,
        # capped at -10. A modest overdraft is survivable; ruinous debt is not.
        penalty = min(10, 3 + (-r.treasury) // 1000)
        r.stability = _clamp(r.stability - penalty)
        g.emit(f"The crown owes {-r.treasury}g; the court grows uneasy "
               f"(-{penalty} stability).")

    # Excellence erodes without upkeep: a contented realm drifts back toward the
    # middle each year, so holding stability high takes active spending (feasts,
    # easing revolts) rather than coasting. Only bites above the midpoint.
    if r.stability > 50:
        r.stability = _clamp(r.stability - 1)

    # Prosperity trends toward stability — a content realm grows wealthy, but
    # reaching 100 prosperity demands sustained 100 stability (rare). This stops
    # prosperity from auto-pinning at the cap mid-reign.
    target = r.stability
    if r.prosperity < target:
        r.prosperity = _clamp(r.prosperity + 2)
    elif r.prosperity > target:
        r.prosperity = _clamp(r.prosperity - 1)
    # Population grows in prosperous times, shrinks in poor ones.
    growth = (r.population * (1 if r.prosperity >= 55 else -1)) // 50
    r.population = max(0, r.population + growth)


def phase_war(g: Game) -> None:
    r = g.realm
    for n in g.neighbors:
        if not n.at_war:
            # A much stronger, hostile neighbour may invade (unless on cooldown).
            if (n.cooldown == 0 and n.relation < -40
                    and n.strength > r.army * 1.5 and g.rng.random() < 0.3):
                n.at_war = True
                g.emit(f"{n.name} senses weakness and invades!")
        if not n.at_war:
            continue
        our_power = r.army * (1 + g.ruler.martial / 50) * (r.stability / 50)
        their_power = n.strength * g.rng.uniform(0.7, 1.3)
        if our_power >= their_power:
            loot = g.rng.randint(40, 120)
            losses = g.rng.randint(20, 80)
            _apply(g, treasury=+loot, army=-losses, legitimacy=+5, stability=+2)
            n.strength = max(50, n.strength - g.rng.randint(40, 100))
            n.relation = _clamp(n.relation - 20, -100, 100)
            n.at_war = False
            n.cooldown = 2
            g.emit(f"Victory over {n.name}! Plunder: +{loot}g, "
                   f"losses: {losses} troops.")
        else:
            losses = g.rng.randint(60, 150)
            indemnity = g.rng.randint(30, 90)
            _apply(g, army=-losses, treasury=-indemnity, stability=-8,
                   legitimacy=-6)
            n.relation = _clamp(n.relation - 10, -100, 100)
            n.at_war = False
            n.cooldown = 2
            g.emit(f"Defeat by {n.name}. Losses: {losses} troops, "
                   f"indemnity: -{indemnity}g.")
            # A catastrophic defeat can kill the ruler on the field.
            if g.rng.random() < 0.10:
                g.emit(f"{g.ruler.name} falls in battle!")
                _kill_ruler(g)


def phase_aging(g: Game) -> None:
    g.ruler.age += 1
    for p in g.family:
        if p.alive:
            p.age += 1

    # Procreation: a married ruler of childbearing prospects may gain an heir.
    spouse = _spouse(g)
    if spouse and g.ruler.age < 48 and spouse.age < 45 and g.rng.random() < 0.30:
        child = _new_person(g, "child", age=0)
        g.family.append(child)
        g.emit(f"A child is born to the royal house: {child.name}.")

    # Mortality rises with age. Applies to ruler and family alike.
    for p in [g.ruler] + list(g.family):
        if not p.alive:
            continue
        chance = 0.01 + max(0, p.age - 50) * 0.015
        if p.age > 70:
            chance += 0.05
        if g.rng.random() < chance:
            if p is g.ruler:
                g.emit(f"{g.ruler.name} dies, aged {g.ruler.age}.")
                _kill_ruler(g)
            else:
                p.alive = False


def _kill_ruler(g: Game) -> None:
    """Resolve succession to exactly one heir, or a defined crisis (game over)."""
    if g.over:
        return
    g.ruler.alive = False
    heir = _choose_heir(g)
    if heir is None:
        g.over = True
        g.over_reason = "The dynasty is extinguished — no heir remains."
        g.emit(g.over_reason)
        return
    old = g.ruler
    g.family = [p for p in g.family if p is not heir and p.alive]
    heir.rel = "ruler"
    g.ruler = heir
    g.realm.stability = _clamp(g.realm.stability - 10)
    g.realm.legitimacy = _clamp(g.realm.legitimacy - 5)
    # Surviving spouse of old ruler departs the model; new ruler may remarry later.
    g.emit(f"{heir.name} ascends the throne (succeeding {old.name}). "
           f"The transition shakes the realm.")
    # Give the new ruler a spouse if of age and unmarried, to keep the line
    # going. A younger heir can later wed via the "Take a spouse" decree.
    if heir.age >= 16 and not _spouse(g) and g.rng.random() < 0.7:
        sg = "f" if heir.gender == "m" else "m"
        g.family.append(_new_person(g, "spouse", age=max(18, heir.age - 4),
                                    gender=sg))


def prestige_score(g: Game) -> int:
    """A single number summarising a reign — shown at game over."""
    r = g.realm
    return max(0, g.turn * 10 + r.legitimacy + r.stability + r.prosperity
               + max(0, r.treasury) // 10 + r.population // 200)


def _choose_heir(g: Game) -> Person | None:
    children = sorted(_living(g, "child"), key=lambda p: -p.age)
    if children:
        return children[0]
    siblings = sorted(_living(g, "sibling"), key=lambda p: -p.age)
    if siblings:
        return siblings[0]
    return None


# --------------------------------------------------------------------------- #
# Turn orchestration
# --------------------------------------------------------------------------- #
def process_turn(g: Game, choose) -> None:
    """Advance one turn. `choose(prompt, options)` -> selected index.

    options is a list of (label, action) where action() applies an effect and
    returns a result string.
    """
    g.turn += 1
    g.year += 1
    g.log = []
    g.emit(f"=== Year {g.year} (turn {g.turn}) — {g.ruler.name} of {g.realm.name} ===")

    phase_economy(g)
    if g.over:
        return

    # Event phase — never the same template twice in a row.
    pool = [e for e in EVENTS if e.__name__ != g.last_event] or EVENTS
    factory = g.rng.choice(pool)
    g.last_event = factory.__name__
    prompt, opts = factory(g)
    idx = choose("EVENT: " + prompt, [label for label, _ in opts])
    g.emit("EVENT: " + prompt)
    g.emit("  > " + opts[idx][1]())
    if g.over:
        return

    # Decree phase
    dopts = decree_options(g)
    idx = choose("DECREE: choose your action", [label for label, _ in dopts])
    g.emit("DECREE: " + dopts[idx][0])
    g.emit("  > " + dopts[idx][1]())

    phase_war(g)
    if g.over:
        return
    phase_aging(g)


# --------------------------------------------------------------------------- #
# Invariants — the contract the simulation must never violate.
# --------------------------------------------------------------------------- #
def check_invariants(g: Game) -> None:
    r = g.realm
    assert isinstance(r.treasury, int), "treasury must be integer"
    assert r.army >= 0, f"army negative: {r.army}"
    assert r.population >= 0, f"population negative: {r.population}"
    for f in STAT_FIELDS:
        v = getattr(r, f)
        assert 0 <= v <= 100, f"{f} out of bounds: {v}"
    assert 0 <= r.tax_rate <= 100, f"tax_rate out of bounds: {r.tax_rate}"
    assert g.ruler.age >= 0, "ruler age negative"
    # Exactly one living ruler unless the game is over. Game-over only happens
    # via a succession crisis, so it implies: a reason, a dead ruler, no heir.
    if g.over:
        assert g.over_reason, "game over must carry a reason"
        assert not g.ruler.alive, "game over implies the ruler has died"
        assert _choose_heir(g) is None, "game over only when no heir remains"
    else:
        assert g.ruler.alive, "ruling monarch must be alive"
        assert g.ruler.rel == "ruler"
    for n in g.neighbors:
        assert -100 <= n.relation <= 100, f"relation out of bounds: {n.relation}"
        assert n.strength >= 0


# --------------------------------------------------------------------------- #
# Self-play harness
# --------------------------------------------------------------------------- #
def self_play(seed: int, turns: int = 30, verbose: bool = False) -> Game:
    g = new_game(seed)
    check_invariants(g)
    for _ in range(turns):
        if g.over:
            break
        process_turn(g, lambda *a: g.rng.randrange(len(a[1])))
        check_invariants(g)
        if verbose:
            for line in g.log:
                print(line)
    return g


def run_harness(seeds: int = 10, turns: int = 30) -> bool:
    ok = True
    for seed in range(seeds):
        try:
            g = self_play(seed, turns)
            status = "GAME OVER" if g.over else "reigning"
            print(f"seed {seed:>3}: turn {g.turn:>2}/{turns}, {status}; "
                  f"treasury={g.realm.treasury}g army={g.realm.army} "
                  f"stab={g.realm.stability} prosp={g.realm.prosperity}")
        except AssertionError as e:
            ok = False
            print(f"seed {seed:>3}: FAIL — invariant violated: {e}")
        except Exception as e:  # noqa: BLE001 — harness must report any crash
            ok = False
            print(f"seed {seed:>3}: FAIL — crash: {type(e).__name__}: {e}")
    print("PASS" if ok else "FAIL")
    return ok


# --------------------------------------------------------------------------- #
# Interactive CLI
# --------------------------------------------------------------------------- #
def _print_status(g: Game) -> None:
    r = g.realm
    print()
    print(f"  Year {g.year} | {g.realm.name} | Ruler: {g.ruler.title} "
          f"[{', '.join(g.ruler.traits)}]")
    print(f"  Gold {r.treasury}g | Tax {r.tax_rate}% | Army {r.army} | "
          f"Pop {r.population}")
    print(f"  Prosperity {r.prosperity} | Stability {r.stability} | "
          f"Legitimacy {r.legitimacy}")
    heirs = _living(g, "child") + _living(g, "sibling")
    print("  Heirs: " + (", ".join(h.title for h in heirs) if heirs else "NONE!"))
    print("  Neighbours: " + ", ".join(
        f"{n.name}({n.relation:+d}{',WAR' if n.at_war else ''})"
        for n in g.neighbors))


def _ask_human(prompt: str, options: list) -> int:
    print("\n" + prompt)
    for i, label in enumerate(options):
        print(f"   [{i + 1}] {label}")
    while True:
        raw = input("   > ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return int(raw) - 1
        print(f"   Enter 1-{len(options)}.")


def play(seed: int | None = None) -> None:
    if seed is None:
        seed = random.randint(0, 10**9)
    g = new_game(seed)
    print("=" * 64)
    print(f"  REALM — you are {g.ruler.name}, ruler of {g.realm.name}.")
    print("  Keep your dynasty on the throne. (Ctrl+C to abdicate.)")
    print("=" * 64)
    try:
        while not g.over:
            _print_status(g)
            process_turn(g, _ask_human)
            for line in g.log:
                if line.startswith(("EVENT", "DECREE", "  >")) or "===" not in line:
                    print(line)
        _print_status(g)
        print("\n*** " + g.over_reason + " ***")
        print(f"Your dynasty ruled {g.realm.name} for {g.turn} years.")
        print(f"Final prestige: {prestige_score(g)}")
    except (KeyboardInterrupt, EOFError):
        print(f"\nYou abdicate the throne after {g.turn} years. "
              f"Prestige: {prestige_score(g)}. Farewell.")


def main(argv: list) -> int:
    if len(argv) > 1 and argv[1] == "--selfplay":
        seeds = int(argv[2]) if len(argv) > 2 else 10
        turns = int(argv[3]) if len(argv) > 3 else 30
        return 0 if run_harness(seeds, turns) else 1
    seed = int(argv[2]) if len(argv) > 2 and argv[1] == "--seed" else None
    play(seed)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
